# 项目配置
project:
  name: 基于spring boot的后端系统
  version: 1.0.1
  upload: D:/project

server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tour?serverTimezone=Asia/Shanghai
    username: root
    password: root

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 1
      connect-timeout: 86400000ms
      lettuce:
        pool:
          max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 5     # 连接池最大空闲连接数
          min-idle: 0     # 连接池最小空闲连接数
          max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
# 日志配置
logging:
  level:
    com.xpf.background: debug
    root: warn

# jwt配置
jwt:
  security:
    key: abcdefghijklmnopqrstuvwxyz
    # 过期时间
    expired: 86400000

# mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:/com/xpf/background/mybatis/mapper/*.xml

