/*
 Navicat Premium Data Transfer

 Source Server         : MySQL8.0
 Source Server Type    : MySQL
 Source Server Version : 80012
 Source Host           : localhost:3306
 Source Schema         : tour

 Target Server Type    : MySQL
 Target Server Version : 80012
 File Encoding         : 65001

 Date: 15/11/2024 09:28:36
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for address
-- ----------------------------
DROP TABLE IF EXISTS `address`;
CREATE TABLE `address`  (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `address` varchar(2550) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '地址(省份)',
  `code` varchar(2550) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '邮政编码',
  `info` varchar(2550) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '旅游景点',
  `city` varchar(2550) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '市区',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 35 CHARACTER SET = utf8 COLLATE = utf8_unicode_ci COMMENT = '旅游地址表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of address
-- ----------------------------
INSERT INTO `address` VALUES (1, '北京市', NULL, NULL, '[{\"cityName\":\"北京市\",\"cityType\":\"直辖市\"}]');
INSERT INTO `address` VALUES (2, '天津市', NULL, NULL, '[{\"cityName\":\"天津市\",\"cityType\":\"直辖市\"}]');
INSERT INTO `address` VALUES (3, '上海市', NULL, NULL, '[{\"cityName\":\"上海市\",\"cityType\":\"直辖市\"}]');
INSERT INTO `address` VALUES (4, '重庆市', NULL, NULL, '[{\"cityName\":\"重庆市\",\"cityType\":\"直辖市\"}]');
INSERT INTO `address` VALUES (5, '香港特别行政区', NULL, NULL, '[{\"cityName\":\"香港特别行政区\",\"cityType\":\"特别行政区\"}]');
INSERT INTO `address` VALUES (6, '澳门特别行政区', NULL, NULL, '[{\"cityName\":\"澳门特别行政区\",\"cityType\":\"特别行政区\"}]');
INSERT INTO `address` VALUES (7, '河北省', NULL, NULL, '[{\"cityName\":\"石家庄市\",\"cityType\":\"地级市\"},{\"cityName\":\"唐山市\",\"cityType\":\"地级市\"},{\"cityName\":\"秦皇岛市\",\"cityType\":\"地级市\"},{\"cityName\":\"邯郸市\",\"cityType\":\"地级市\"},{\"cityName\":\"邢台市\",\"cityType\":\"地级市\"},{\"cityName\":\"保定市\",\"cityType\":\"地级市\"},{\"cityName\":\"张家口市\",\"cityType\":\"地级市\"},{\"cityName\":\"承德市\",\"cityType\":\"地级市\"},{\"cityName\":\"沧州市\",\"cityType\":\"地级市\"},{\"cityName\":\"廊坊市\",\"cityType\":\"地级市\"},{\"cityName\":\"衡水市\",\"cityType\":\"地级市\"},{\"cityName\":\"辛集市\",\"cityType\":\"县级市\"},{\"cityName\":\"晋州市\",\"cityType\":\"县级市\"},{\"cityName\":\"新乐市\",\"cityType\":\"县级市\"},{\"cityName\":\"遵化市\",\"cityType\":\"县级市\"},{\"cityName\":\"迁安市\",\"cityType\":\"县级市\"},{\"cityName\":\"武安市\",\"cityType\":\"县级市\"},{\"cityName\":\"南宫市\",\"cityType\":\"县级市\"},{\"cityName\":\"沙河市\",\"cityType\":\"县级市\"},{\"cityName\":\"涿州市\",\"cityType\":\"县级市\"},{\"cityName\":\"定州市\",\"cityType\":\"县级市\"},{\"cityName\":\"安国市\",\"cityType\":\"县级市\"},{\"cityName\":\"高碑店市\",\"cityType\":\"县级市\"},{\"cityName\":\"平泉市\",\"cityType\":\"县级市\"},{\"cityName\":\"泊头市\",\"cityType\":\"县级市\"},{\"cityName\":\"任丘市\",\"cityType\":\"县级市\"},{\"cityName\":\"黄骅市\",\"cityType\":\"县级市\"},{\"cityName\":\"河间市\",\"cityType\":\"县级市\"},{\"cityName\":\"霸州市\",\"cityType\":\"县级市\"},{\"cityName\":\"三河市\",\"cityType\":\"县级市\"},{\"cityName\":\"深州市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (8, '山西省', NULL, NULL, '[{\"cityName\":\"太原市\",\"cityType\":\"地级市\"},{\"cityName\":\"大同市\",\"cityType\":\"地级市\"},{\"cityName\":\"阳泉市\",\"cityType\":\"地级市\"},{\"cityName\":\"长治市\",\"cityType\":\"地级市\"},{\"cityName\":\"晋城市\",\"cityType\":\"地级市\"},{\"cityName\":\"朔州市\",\"cityType\":\"地级市\"},{\"cityName\":\"晋中市\",\"cityType\":\"地级市\"},{\"cityName\":\"运城市\",\"cityType\":\"地级市\"},{\"cityName\":\"忻州市\",\"cityType\":\"地级市\"},{\"cityName\":\"临汾市\",\"cityType\":\"地级市\"},{\"cityName\":\"吕梁市\",\"cityType\":\"地级市\"},{\"cityName\":\"古交市\",\"cityType\":\"县级市\"},{\"cityName\":\"高平市\",\"cityType\":\"县级市\"},{\"cityName\":\"介休市\",\"cityType\":\"县级市\"},{\"cityName\":\"永济市\",\"cityType\":\"县级市\"},{\"cityName\":\"河津市\",\"cityType\":\"县级市\"},{\"cityName\":\"原平市\",\"cityType\":\"县级市\"},{\"cityName\":\"侯马市\",\"cityType\":\"县级市\"},{\"cityName\":\"霍州市\",\"cityType\":\"县级市\"},{\"cityName\":\"孝义市\",\"cityType\":\"县级市\"},{\"cityName\":\"汾阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"怀仁市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (9, '内蒙古自治区', NULL, NULL, '[{\"cityName\":\"呼和浩特市\",\"cityType\":\"地级市\"},{\"cityName\":\"包头市\",\"cityType\":\"地级市\"},{\"cityName\":\"乌海市\",\"cityType\":\"地级市\"},{\"cityName\":\"赤峰市\",\"cityType\":\"地级市\"},{\"cityName\":\"通辽市\",\"cityType\":\"地级市\"},{\"cityName\":\"鄂尔多斯市\",\"cityType\":\"地级市\"},{\"cityName\":\"呼伦贝尔市\",\"cityType\":\"地级市\"},{\"cityName\":\"巴彦淖尔市\",\"cityType\":\"地级市\"},{\"cityName\":\"乌兰察布市\",\"cityType\":\"地级市\"},{\"cityName\":\"霍林郭勒市\",\"cityType\":\"县级市\"},{\"cityName\":\"满洲里市\",\"cityType\":\"县级市\"},{\"cityName\":\"牙克石市\",\"cityType\":\"县级市\"},{\"cityName\":\"扎兰屯市\",\"cityType\":\"县级市\"},{\"cityName\":\"额尔古纳市\",\"cityType\":\"县级市\"},{\"cityName\":\"根河市\",\"cityType\":\"县级市\"},{\"cityName\":\"丰镇市\",\"cityType\":\"县级市\"},{\"cityName\":\"乌兰浩特市\",\"cityType\":\"县级市\"},{\"cityName\":\"阿尔山市\",\"cityType\":\"县级市\"},{\"cityName\":\"二连浩特市\",\"cityType\":\"县级市\"},{\"cityName\":\"锡林浩特市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (10, '辽宁省', NULL, NULL, '[{\"cityName\":\"沈阳市\",\"cityType\":\"地级市\"},{\"cityName\":\"大连市\",\"cityType\":\"地级市\"},{\"cityName\":\"鞍山市\",\"cityType\":\"县级市\"},{\"cityName\":\"抚顺市\",\"cityType\":\"县级市\"},{\"cityName\":\"本溪市\",\"cityType\":\"县级市\"},{\"cityName\":\"丹东市\",\"cityType\":\"县级市\"},{\"cityName\":\"锦州市\",\"cityType\":\"县级市\"},{\"cityName\":\"营口市\",\"cityType\":\"县级市\"},{\"cityName\":\"阜新市\",\"cityType\":\"县级市\"},{\"cityName\":\"辽阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"盘锦市\",\"cityType\":\"县级市\"},{\"cityName\":\"铁岭市\",\"cityType\":\"县级市\"},{\"cityName\":\"朝阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"葫芦岛市\",\"cityType\":\"县级市\"},{\"cityName\":\"新民市\",\"cityType\":\"县级市\"},{\"cityName\":\"瓦房店市\",\"cityType\":\"县级市\"},{\"cityName\":\"庄河市\",\"cityType\":\"县级市\"},{\"cityName\":\"海城市\",\"cityType\":\"县级市\"},{\"cityName\":\"东港市\",\"cityType\":\"县级市\"},{\"cityName\":\"凤城市\",\"cityType\":\"县级市\"},{\"cityName\":\"凌海市\",\"cityType\":\"县级市\"},{\"cityName\":\"北镇市\",\"cityType\":\"县级市\"},{\"cityName\":\"盖州市\",\"cityType\":\"县级市\"},{\"cityName\":\"大石桥市\",\"cityType\":\"县级市\"},{\"cityName\":\"灯塔市\",\"cityType\":\"县级市\"},{\"cityName\":\"调兵山市\",\"cityType\":\"县级市\"},{\"cityName\":\"开原市\",\"cityType\":\"县级市\"},{\"cityName\":\"北票市\",\"cityType\":\"县级市\"},{\"cityName\":\"凌源市\",\"cityType\":\"县级市\"},{\"cityName\":\"兴城市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (11, '吉林省', NULL, NULL, '[{\"cityName\":\"长春市\",\"cityType\":\"地级市\"},{\"cityName\":\"吉林市\",\"cityType\":\"县级市\"},{\"cityName\":\"四平市\",\"cityType\":\"县级市\"},{\"cityName\":\"辽源市\",\"cityType\":\"县级市\"},{\"cityName\":\"通化市\",\"cityType\":\"县级市\"},{\"cityName\":\"白山市\",\"cityType\":\"县级市\"},{\"cityName\":\"松原市\",\"cityType\":\"县级市\"},{\"cityName\":\"白城市\",\"cityType\":\"县级市\"},{\"cityName\":\"榆树市\",\"cityType\":\"县级市\"},{\"cityName\":\"德惠市\",\"cityType\":\"县级市\"},{\"cityName\":\"蛟河市\",\"cityType\":\"县级市\"},{\"cityName\":\"桦甸市\",\"cityType\":\"县级市\"},{\"cityName\":\"舒兰市\",\"cityType\":\"县级市\"},{\"cityName\":\"磐石市\",\"cityType\":\"县级市\"},{\"cityName\":\"公主岭市\",\"cityType\":\"县级市\"},{\"cityName\":\"双辽市\",\"cityType\":\"县级市\"},{\"cityName\":\"梅河口市\",\"cityType\":\"县级市\"},{\"cityName\":\"集安市\",\"cityType\":\"县级市\"},{\"cityName\":\"洮南市\",\"cityType\":\"县级市\"},{\"cityName\":\"大安市\",\"cityType\":\"县级市\"},{\"cityName\":\"临江市\",\"cityType\":\"县级市\"},{\"cityName\":\"延吉市\",\"cityType\":\"县级市\"},{\"cityName\":\"图们市\",\"cityType\":\"县级市\"},{\"cityName\":\"敦化市\",\"cityType\":\"县级市\"},{\"cityName\":\"珲春市\",\"cityType\":\"县级市\"},{\"cityName\":\"龙井市\",\"cityType\":\"县级市\"},{\"cityName\":\"和龙市\",\"cityType\":\"县级市\"},{\"cityName\":\"扶余市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (12, '黑龙江省', NULL, NULL, '[{\"cityName\":\"哈尔滨市\",\"cityType\":\"地级市\"},{\"cityName\":\"齐齐哈尔市\",\"cityType\":\"县级市\"},{\"cityName\":\"黑河市\",\"cityType\":\"县级市\"},{\"cityName\":\"大庆市\",\"cityType\":\"县级市\"},{\"cityName\":\"伊春市\",\"cityType\":\"县级市\"},{\"cityName\":\"鹤岗市\",\"cityType\":\"县级市\"},{\"cityName\":\"佳木斯市\",\"cityType\":\"县级市\"},{\"cityName\":\"双鸭山市\",\"cityType\":\"县级市\"},{\"cityName\":\"七台河市\",\"cityType\":\"县级市\"},{\"cityName\":\"鸡西市\",\"cityType\":\"县级市\"},{\"cityName\":\"牡丹江市\",\"cityType\":\"县级市\"},{\"cityName\":\"绥化市\",\"cityType\":\"县级市\"},{\"cityName\":\"尚志市\",\"cityType\":\"县级市\"},{\"cityName\":\"五常市\",\"cityType\":\"县级市\"},{\"cityName\":\"讷河市\",\"cityType\":\"县级市\"},{\"cityName\":\"北安市\",\"cityType\":\"县级市\"},{\"cityName\":\"五大连池市\",\"cityType\":\"县级市\"},{\"cityName\":\"嫩江市\",\"cityType\":\"县级市\"},{\"cityName\":\"铁力市\",\"cityType\":\"县级市\"},{\"cityName\":\"同江市\",\"cityType\":\"县级市\"},{\"cityName\":\"富锦市\",\"cityType\":\"县级市\"},{\"cityName\":\"虎林市\",\"cityType\":\"县级市\"},{\"cityName\":\"密山市\",\"cityType\":\"县级市\"},{\"cityName\":\"绥芬河市\",\"cityType\":\"县级市\"},{\"cityName\":\"海林市\",\"cityType\":\"县级市\"},{\"cityName\":\"宁安市\",\"cityType\":\"县级市\"},{\"cityName\":\"安达市\",\"cityType\":\"县级市\"},{\"cityName\":\"肇东市\",\"cityType\":\"县级市\"},{\"cityName\":\"海伦市\",\"cityType\":\"县级市\"},{\"cityName\":\"穆棱市\",\"cityType\":\"县级市\"},{\"cityName\":\"东宁市\",\"cityType\":\"县级市\"},{\"cityName\":\"抚远市\",\"cityType\":\"县级市\"},{\"cityName\":\"漠河市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (13, '江苏省', NULL, NULL, '[{\"cityName\":\"南京市\",\"cityType\":\"地级市\"},{\"cityName\":\"徐州市\",\"cityType\":\"县级市\"},{\"cityName\":\"连云港市\",\"cityType\":\"县级市\"},{\"cityName\":\"宿迁市\",\"cityType\":\"县级市\"},{\"cityName\":\"淮安市\",\"cityType\":\"县级市\"},{\"cityName\":\"盐城市\",\"cityType\":\"县级市\"},{\"cityName\":\"扬州市\",\"cityType\":\"县级市\"},{\"cityName\":\"泰州市\",\"cityType\":\"县级市\"},{\"cityName\":\"南通市\",\"cityType\":\"县级市\"},{\"cityName\":\"镇江市\",\"cityType\":\"县级市\"},{\"cityName\":\"常州市\",\"cityType\":\"县级市\"},{\"cityName\":\"无锡市\",\"cityType\":\"县级市\"},{\"cityName\":\"苏州市\",\"cityType\":\"县级市\"},{\"cityName\":\"常熟市\",\"cityType\":\"县级市\"},{\"cityName\":\"张家港市\",\"cityType\":\"县级市\"},{\"cityName\":\"太仓市\",\"cityType\":\"县级市\"},{\"cityName\":\"昆山市\",\"cityType\":\"县级市\"},{\"cityName\":\"江阴市\",\"cityType\":\"县级市\"},{\"cityName\":\"宜兴市\",\"cityType\":\"县级市\"},{\"cityName\":\"溧阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"扬中市\",\"cityType\":\"县级市\"},{\"cityName\":\"句容市\",\"cityType\":\"县级市\"},{\"cityName\":\"丹阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"如皋市\",\"cityType\":\"县级市\"},{\"cityName\":\"启东市\",\"cityType\":\"县级市\"},{\"cityName\":\"海安市\",\"cityType\":\"县级市\"},{\"cityName\":\"高邮市\",\"cityType\":\"县级市\"},{\"cityName\":\"仪征市\",\"cityType\":\"县级市\"},{\"cityName\":\"兴化市\",\"cityType\":\"县级市\"},{\"cityName\":\"泰兴市\",\"cityType\":\"县级市\"},{\"cityName\":\"靖江市\",\"cityType\":\"县级市\"},{\"cityName\":\"东台市\",\"cityType\":\"县级市\"},{\"cityName\":\"邳州市\",\"cityType\":\"县级市\"},{\"cityName\":\"新沂市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (14, '浙江省', NULL, NULL, '[{\"cityName\":\"杭州市\",\"cityType\":\"地级市\"},{\"cityName\":\"宁波市\",\"cityType\":\"地级市\"},{\"cityName\":\"湖州市\",\"cityType\":\"县级市\"},{\"cityName\":\"嘉兴市\",\"cityType\":\"县级市\"},{\"cityName\":\"舟山市\",\"cityType\":\"县级市\"},{\"cityName\":\"绍兴市\",\"cityType\":\"县级市\"},{\"cityName\":\"衢州市\",\"cityType\":\"县级市\"},{\"cityName\":\"金华市\",\"cityType\":\"县级市\"},{\"cityName\":\"台州市\",\"cityType\":\"县级市\"},{\"cityName\":\"温州市\",\"cityType\":\"县级市\"},{\"cityName\":\"丽水市\",\"cityType\":\"县级市\"},{\"cityName\":\"建德市\",\"cityType\":\"县级市\"},{\"cityName\":\"慈溪市\",\"cityType\":\"县级市\"},{\"cityName\":\"余姚市\",\"cityType\":\"县级市\"},{\"cityName\":\"平湖市\",\"cityType\":\"县级市\"},{\"cityName\":\"海宁市\",\"cityType\":\"县级市\"},{\"cityName\":\"桐乡市\",\"cityType\":\"县级市\"},{\"cityName\":\"诸暨市\",\"cityType\":\"县级市\"},{\"cityName\":\"嵊州市\",\"cityType\":\"县级市\"},{\"cityName\":\"江山市\",\"cityType\":\"县级市\"},{\"cityName\":\"兰溪市\",\"cityType\":\"县级市\"},{\"cityName\":\"永康市\",\"cityType\":\"县级市\"},{\"cityName\":\"义乌市\",\"cityType\":\"县级市\"},{\"cityName\":\"东阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"临海市\",\"cityType\":\"县级市\"},{\"cityName\":\"温岭市\",\"cityType\":\"县级市\"},{\"cityName\":\"瑞安市\",\"cityType\":\"县级市\"},{\"cityName\":\"乐清市\",\"cityType\":\"县级市\"},{\"cityName\":\"龙港市\",\"cityType\":\"县级市\"},{\"cityName\":\"龙泉市\",\"cityType\":\"县级市\"},{\"cityName\":\"玉环市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (15, '安徽省', NULL, NULL, '[{\"cityName\":\"合肥市\",\"cityType\":\"地级市\"},{\"cityName\":\"芜湖市\",\"cityType\":\"地级市\"},{\"cityName\":\"蚌埠市\",\"cityType\":\"地级市\"},{\"cityName\":\"淮南市\",\"cityType\":\"地级市\"},{\"cityName\":\"马鞍山市\",\"cityType\":\"地级市\"},{\"cityName\":\"淮北市\",\"cityType\":\"地级市\"},{\"cityName\":\"铜陵市\",\"cityType\":\"地级市\"},{\"cityName\":\"安庆市\",\"cityType\":\"地级市\"},{\"cityName\":\"黄山市\",\"cityType\":\"地级市\"},{\"cityName\":\"滁州市\",\"cityType\":\"地级市\"},{\"cityName\":\"阜阳市\",\"cityType\":\"地级市\"},{\"cityName\":\"宿州市\",\"cityType\":\"地级市\"},{\"cityName\":\"六安市\",\"cityType\":\"地级市\"},{\"cityName\":\"亳州市\",\"cityType\":\"地级市\"},{\"cityName\":\"池州市\",\"cityType\":\"地级市\"},{\"cityName\":\"宣城市\",\"cityType\":\"地级市\"},{\"cityName\":\"巢湖市\",\"cityType\":\"县级市\"},{\"cityName\":\"桐城市\",\"cityType\":\"县级市\"},{\"cityName\":\"天长市\",\"cityType\":\"县级市\"},{\"cityName\":\"明光市\",\"cityType\":\"县级市\"},{\"cityName\":\"界首市\",\"cityType\":\"县级市\"},{\"cityName\":\"宁国市\",\"cityType\":\"县级市\"},{\"cityName\":\"广德市\",\"cityType\":\"县级市\"},{\"cityName\":\"潜山市\",\"cityType\":\"县级市\"},{\"cityName\":\"无为市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (16, '福建省', NULL, NULL, '[{\"cityName\":\"厦门市\",\"cityType\":\"地级市\"},{\"cityName\":\"福州市\",\"cityType\":\"县级市\"},{\"cityName\":\"南平市\",\"cityType\":\"县级市\"},{\"cityName\":\"三明市\",\"cityType\":\"县级市\"},{\"cityName\":\"莆田市\",\"cityType\":\"县级市\"},{\"cityName\":\"泉州市\",\"cityType\":\"县级市\"},{\"cityName\":\"漳州市\",\"cityType\":\"县级市\"},{\"cityName\":\"龙岩市\",\"cityType\":\"县级市\"},{\"cityName\":\"宁德市\",\"cityType\":\"县级市\"},{\"cityName\":\"福清市\",\"cityType\":\"县级市\"},{\"cityName\":\"邵武市\",\"cityType\":\"县级市\"},{\"cityName\":\"武夷山市\",\"cityType\":\"县级市\"},{\"cityName\":\"建瓯市\",\"cityType\":\"县级市\"},{\"cityName\":\"永安市\",\"cityType\":\"县级市\"},{\"cityName\":\"石狮市\",\"cityType\":\"县级市\"},{\"cityName\":\"晋江市\",\"cityType\":\"县级市\"},{\"cityName\":\"南安市\",\"cityType\":\"县级市\"},{\"cityName\":\"龙海市\",\"cityType\":\"县级市\"},{\"cityName\":\"漳平市\",\"cityType\":\"县级市\"},{\"cityName\":\"福安市\",\"cityType\":\"县级市\"},{\"cityName\":\"福鼎市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (17, '江西省', NULL, NULL, '[{\"cityName\":\"南昌市\",\"cityType\":\"地级市\"},{\"cityName\":\"九江市\",\"cityType\":\"地级市\"},{\"cityName\":\"景德镇市\",\"cityType\":\"地级市\"},{\"cityName\":\"鹰潭市\",\"cityType\":\"地级市\"},{\"cityName\":\"新余市\",\"cityType\":\"地级市\"},{\"cityName\":\"萍乡市\",\"cityType\":\"地级市\"},{\"cityName\":\"赣州市\",\"cityType\":\"地级市\"},{\"cityName\":\"上饶市\",\"cityType\":\"地级市\"},{\"cityName\":\"抚州市\",\"cityType\":\"地级市\"},{\"cityName\":\"宜春市\",\"cityType\":\"地级市\"},{\"cityName\":\"吉安市\",\"cityType\":\"地级市\"},{\"cityName\":\"瑞昌市\",\"cityType\":\"县级市\"},{\"cityName\":\"共青城市\",\"cityType\":\"县级市\"},{\"cityName\":\"庐山市\",\"cityType\":\"县级市\"},{\"cityName\":\"乐平市\",\"cityType\":\"县级市\"},{\"cityName\":\"瑞金市\",\"cityType\":\"县级市\"},{\"cityName\":\"德兴市\",\"cityType\":\"县级市\"},{\"cityName\":\"丰城市\",\"cityType\":\"县级市\"},{\"cityName\":\"樟树市\",\"cityType\":\"县级市\"},{\"cityName\":\"高安市\",\"cityType\":\"县级市\"},{\"cityName\":\"井冈山市\",\"cityType\":\"县级市\"},{\"cityName\":\"贵溪市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (18, '山东省', NULL, NULL, '[{\"cityName\":\"济南市\",\"cityType\":\"地级市\"},{\"cityName\":\"青岛市\",\"cityType\":\"地级市\"},{\"cityName\":\"聊城市\",\"cityType\":\"县级市\"},{\"cityName\":\"德州市\",\"cityType\":\"县级市\"},{\"cityName\":\"东营市\",\"cityType\":\"县级市\"},{\"cityName\":\"淄博市\",\"cityType\":\"县级市\"},{\"cityName\":\"潍坊市\",\"cityType\":\"县级市\"},{\"cityName\":\"烟台市\",\"cityType\":\"县级市\"},{\"cityName\":\"威海市\",\"cityType\":\"县级市\"},{\"cityName\":\"日照市\",\"cityType\":\"县级市\"},{\"cityName\":\"临沂市\",\"cityType\":\"县级市\"},{\"cityName\":\"枣庄市\",\"cityType\":\"县级市\"},{\"cityName\":\"济宁市\",\"cityType\":\"县级市\"},{\"cityName\":\"泰安市\",\"cityType\":\"县级市\"},{\"cityName\":\"滨州市\",\"cityType\":\"县级市\"},{\"cityName\":\"菏泽市\",\"cityType\":\"县级市\"},{\"cityName\":\"胶州市\",\"cityType\":\"县级市\"},{\"cityName\":\"平度市\",\"cityType\":\"县级市\"},{\"cityName\":\"莱西市\",\"cityType\":\"县级市\"},{\"cityName\":\"临清市\",\"cityType\":\"县级市\"},{\"cityName\":\"乐陵市\",\"cityType\":\"县级市\"},{\"cityName\":\"禹城市\",\"cityType\":\"县级市\"},{\"cityName\":\"安丘市\",\"cityType\":\"县级市\"},{\"cityName\":\"昌邑市\",\"cityType\":\"县级市\"},{\"cityName\":\"高密市\",\"cityType\":\"县级市\"},{\"cityName\":\"青州市\",\"cityType\":\"县级市\"},{\"cityName\":\"诸城市\",\"cityType\":\"县级市\"},{\"cityName\":\"寿光市\",\"cityType\":\"县级市\"},{\"cityName\":\"栖霞市\",\"cityType\":\"县级市\"},{\"cityName\":\"海阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"龙口市\",\"cityType\":\"县级市\"},{\"cityName\":\"莱阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"莱州市\",\"cityType\":\"县级市\"},{\"cityName\":\"蓬莱市\",\"cityType\":\"县级市\"},{\"cityName\":\"招远市\",\"cityType\":\"县级市\"},{\"cityName\":\"荣成市\",\"cityType\":\"县级市\"},{\"cityName\":\"乳山市\",\"cityType\":\"县级市\"},{\"cityName\":\"滕州市\",\"cityType\":\"县级市\"},{\"cityName\":\"曲阜市\",\"cityType\":\"县级市\"},{\"cityName\":\"邹城市\",\"cityType\":\"县级市\"},{\"cityName\":\"新泰市\",\"cityType\":\"县级市\"},{\"cityName\":\"肥城市\",\"cityType\":\"县级市\"},{\"cityName\":\"邹平市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (19, '河南省', NULL, NULL, '[{\"cityName\":\"郑州市\",\"cityType\":\"地级市\"},{\"cityName\":\"开封市\",\"cityType\":\"地级市\"},{\"cityName\":\"洛阳市\",\"cityType\":\"地级市\"},{\"cityName\":\"平顶山市\",\"cityType\":\"地级市\"},{\"cityName\":\"安阳市\",\"cityType\":\"地级市\"},{\"cityName\":\"鹤壁市\",\"cityType\":\"地级市\"},{\"cityName\":\"新乡市\",\"cityType\":\"地级市\"},{\"cityName\":\"焦作市\",\"cityType\":\"地级市\"},{\"cityName\":\"濮阳市\",\"cityType\":\"地级市\"},{\"cityName\":\"许昌市\",\"cityType\":\"地级市\"},{\"cityName\":\"漯河市\",\"cityType\":\"地级市\"},{\"cityName\":\"三门峡市\",\"cityType\":\"地级市\"},{\"cityName\":\"南阳市\",\"cityType\":\"地级市\"},{\"cityName\":\"商丘市\",\"cityType\":\"地级市\"},{\"cityName\":\"周口市\",\"cityType\":\"地级市\"},{\"cityName\":\"驻马店市\",\"cityType\":\"地级市\"},{\"cityName\":\"信阳市\",\"cityType\":\"地级市\"},{\"cityName\":\"荥阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"新郑市\",\"cityType\":\"县级市\"},{\"cityName\":\"登封市\",\"cityType\":\"县级市\"},{\"cityName\":\"新密市\",\"cityType\":\"县级市\"},{\"cityName\":\"偃师市\",\"cityType\":\"县级市\"},{\"cityName\":\"孟州市\",\"cityType\":\"县级市\"},{\"cityName\":\"沁阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"卫辉市\",\"cityType\":\"县级市\"},{\"cityName\":\"辉县市\",\"cityType\":\"县级市\"},{\"cityName\":\"长垣市\",\"cityType\":\"县级市\"},{\"cityName\":\"林州市\",\"cityType\":\"县级市\"},{\"cityName\":\"禹州市\",\"cityType\":\"县级市\"},{\"cityName\":\"长葛市\",\"cityType\":\"县级市\"},{\"cityName\":\"舞钢市\",\"cityType\":\"县级市\"},{\"cityName\":\"义马市\",\"cityType\":\"县级市\"},{\"cityName\":\"灵宝市\",\"cityType\":\"县级市\"},{\"cityName\":\"项城市\",\"cityType\":\"县级市\"},{\"cityName\":\"巩义市\",\"cityType\":\"县级市\"},{\"cityName\":\"邓州市\",\"cityType\":\"县级市\"},{\"cityName\":\"永城市\",\"cityType\":\"县级市\"},{\"cityName\":\"汝州市\",\"cityType\":\"县级市\"},{\"cityName\":\"济源市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (20, '湖北省', NULL, NULL, '[{\"cityName\":\"武汉市\",\"cityType\":\"地级市\"},{\"cityName\":\"十堰市\",\"cityType\":\"县级市\"},{\"cityName\":\"襄阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"荆门市\",\"cityType\":\"县级市\"},{\"cityName\":\"孝感市\",\"cityType\":\"县级市\"},{\"cityName\":\"黄冈市\",\"cityType\":\"县级市\"},{\"cityName\":\"鄂州市\",\"cityType\":\"县级市\"},{\"cityName\":\"黄石市\",\"cityType\":\"县级市\"},{\"cityName\":\"咸宁市\",\"cityType\":\"县级市\"},{\"cityName\":\"荆州市\",\"cityType\":\"县级市\"},{\"cityName\":\"宜昌市\",\"cityType\":\"县级市\"},{\"cityName\":\"随州市\",\"cityType\":\"县级市\"},{\"cityName\":\"丹江口市\",\"cityType\":\"县级市\"},{\"cityName\":\"老河口市\",\"cityType\":\"县级市\"},{\"cityName\":\"枣阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"宜城市\",\"cityType\":\"县级市\"},{\"cityName\":\"钟祥市\",\"cityType\":\"县级市\"},{\"cityName\":\"京山市\",\"cityType\":\"县级市\"},{\"cityName\":\"汉川市\",\"cityType\":\"县级市\"},{\"cityName\":\"应城市\",\"cityType\":\"县级市\"},{\"cityName\":\"安陆市\",\"cityType\":\"县级市\"},{\"cityName\":\"广水市\",\"cityType\":\"县级市\"},{\"cityName\":\"麻城市\",\"cityType\":\"县级市\"},{\"cityName\":\"武穴市\",\"cityType\":\"县级市\"},{\"cityName\":\"大冶市\",\"cityType\":\"县级市\"},{\"cityName\":\"赤壁市\",\"cityType\":\"县级市\"},{\"cityName\":\"石首市\",\"cityType\":\"县级市\"},{\"cityName\":\"洪湖市\",\"cityType\":\"县级市\"},{\"cityName\":\"松滋市\",\"cityType\":\"县级市\"},{\"cityName\":\"宜都市\",\"cityType\":\"县级市\"},{\"cityName\":\"枝江市\",\"cityType\":\"县级市\"},{\"cityName\":\"当阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"恩施市\",\"cityType\":\"县级市\"},{\"cityName\":\"利川市\",\"cityType\":\"县级市\"},{\"cityName\":\"仙桃市\",\"cityType\":\"县级市\"},{\"cityName\":\"天门市\",\"cityType\":\"县级市\"},{\"cityName\":\"潜江市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (21, '湖南省', NULL, NULL, '[{\"cityName\":\"长沙市\",\"cityType\":\"地级市\"},{\"cityName\":\"衡阳市\",\"cityType\":\"地级市\"},{\"cityName\":\"张家界市\",\"cityType\":\"地级市\"},{\"cityName\":\"常德市\",\"cityType\":\"地级市\"},{\"cityName\":\"益阳市\",\"cityType\":\"地级市\"},{\"cityName\":\"岳阳市\",\"cityType\":\"地级市\"},{\"cityName\":\"株洲市\",\"cityType\":\"地级市\"},{\"cityName\":\"湘潭市\",\"cityType\":\"地级市\"},{\"cityName\":\"郴州市\",\"cityType\":\"地级市\"},{\"cityName\":\"永州市\",\"cityType\":\"地级市\"},{\"cityName\":\"邵阳市\",\"cityType\":\"地级市\"},{\"cityName\":\"怀化市\",\"cityType\":\"地级市\"},{\"cityName\":\"娄底市\",\"cityType\":\"地级市\"},{\"cityName\":\"耒阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"常宁市\",\"cityType\":\"县级市\"},{\"cityName\":\"浏阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"津市市\",\"cityType\":\"县级市\"},{\"cityName\":\"沅江市\",\"cityType\":\"县级市\"},{\"cityName\":\"汨罗市\",\"cityType\":\"县级市\"},{\"cityName\":\"临湘市\",\"cityType\":\"县级市\"},{\"cityName\":\"醴陵市\",\"cityType\":\"县级市\"},{\"cityName\":\"湘乡市\",\"cityType\":\"县级市\"},{\"cityName\":\"韶山市\",\"cityType\":\"县级市\"},{\"cityName\":\"资兴市\",\"cityType\":\"县级市\"},{\"cityName\":\"武冈市\",\"cityType\":\"县级市\"},{\"cityName\":\"邵东市\",\"cityType\":\"县级市\"},{\"cityName\":\"洪江市\",\"cityType\":\"县级市\"},{\"cityName\":\"冷水江市\",\"cityType\":\"县级市\"},{\"cityName\":\"涟源市\",\"cityType\":\"县级市\"},{\"cityName\":\"吉首市\",\"cityType\":\"县级市\"},{\"cityName\":\"宁乡市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (22, '广东省', NULL, NULL, '[{\"cityName\":\"广州市\",\"cityType\":\"地级市\"},{\"cityName\":\"深圳市\",\"cityType\":\"地级市\"},{\"cityName\":\"清远市\",\"cityType\":\"县级市\"},{\"cityName\":\"韶关市\",\"cityType\":\"县级市\"},{\"cityName\":\"河源市\",\"cityType\":\"县级市\"},{\"cityName\":\"梅州市\",\"cityType\":\"县级市\"},{\"cityName\":\"潮州市\",\"cityType\":\"县级市\"},{\"cityName\":\"汕头市\",\"cityType\":\"县级市\"},{\"cityName\":\"揭阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"汕尾市\",\"cityType\":\"县级市\"},{\"cityName\":\"惠州市\",\"cityType\":\"县级市\"},{\"cityName\":\"东莞市\",\"cityType\":\"县级市\"},{\"cityName\":\"珠海市\",\"cityType\":\"县级市\"},{\"cityName\":\"中山市\",\"cityType\":\"县级市\"},{\"cityName\":\"江门市\",\"cityType\":\"县级市\"},{\"cityName\":\"佛山市\",\"cityType\":\"县级市\"},{\"cityName\":\"肇庆市\",\"cityType\":\"县级市\"},{\"cityName\":\"云浮市\",\"cityType\":\"县级市\"},{\"cityName\":\"阳江市\",\"cityType\":\"县级市\"},{\"cityName\":\"茂名市\",\"cityType\":\"县级市\"},{\"cityName\":\"湛江市\",\"cityType\":\"县级市\"},{\"cityName\":\"英德市\",\"cityType\":\"县级市\"},{\"cityName\":\"连州市\",\"cityType\":\"县级市\"},{\"cityName\":\"乐昌市\",\"cityType\":\"县级市\"},{\"cityName\":\"南雄市\",\"cityType\":\"县级市\"},{\"cityName\":\"兴宁市\",\"cityType\":\"县级市\"},{\"cityName\":\"普宁市\",\"cityType\":\"县级市\"},{\"cityName\":\"陆丰市\",\"cityType\":\"县级市\"},{\"cityName\":\"恩平市\",\"cityType\":\"县级市\"},{\"cityName\":\"台山市\",\"cityType\":\"县级市\"},{\"cityName\":\"开平市\",\"cityType\":\"县级市\"},{\"cityName\":\"鹤山市\",\"cityType\":\"县级市\"},{\"cityName\":\"四会市\",\"cityType\":\"县级市\"},{\"cityName\":\"罗定市\",\"cityType\":\"县级市\"},{\"cityName\":\"阳春市\",\"cityType\":\"县级市\"},{\"cityName\":\"化州市\",\"cityType\":\"县级市\"},{\"cityName\":\"信宜市\",\"cityType\":\"县级市\"},{\"cityName\":\"高州市\",\"cityType\":\"县级市\"},{\"cityName\":\"吴川市\",\"cityType\":\"县级市\"},{\"cityName\":\"廉江市\",\"cityType\":\"县级市\"},{\"cityName\":\"雷州市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (23, '广西壮族自治区', NULL, NULL, '[{\"cityName\":\"南宁市\",\"cityType\":\"地级市\"},{\"cityName\":\"桂林市\",\"cityType\":\"地级市\"},{\"cityName\":\"柳州市\",\"cityType\":\"地级市\"},{\"cityName\":\"梧州市\",\"cityType\":\"地级市\"},{\"cityName\":\"贵港市\",\"cityType\":\"地级市\"},{\"cityName\":\"玉林市\",\"cityType\":\"地级市\"},{\"cityName\":\"钦州市\",\"cityType\":\"地级市\"},{\"cityName\":\"北海市\",\"cityType\":\"地级市\"},{\"cityName\":\"防城港市\",\"cityType\":\"地级市\"},{\"cityName\":\"崇左市\",\"cityType\":\"地级市\"},{\"cityName\":\"百色市\",\"cityType\":\"地级市\"},{\"cityName\":\"河池市\",\"cityType\":\"地级市\"},{\"cityName\":\"来宾市\",\"cityType\":\"地级市\"},{\"cityName\":\"贺州市\",\"cityType\":\"地级市\"},{\"cityName\":\"岑溪市\",\"cityType\":\"县级市\"},{\"cityName\":\"桂平市\",\"cityType\":\"县级市\"},{\"cityName\":\"北流市\",\"cityType\":\"县级市\"},{\"cityName\":\"东兴市\",\"cityType\":\"县级市\"},{\"cityName\":\"凭祥市\",\"cityType\":\"县级市\"},{\"cityName\":\"合山市\",\"cityType\":\"县级市\"},{\"cityName\":\"靖西市\",\"cityType\":\"县级市\"},{\"cityName\":\"平果市\",\"cityType\":\"县级市\"},{\"cityName\":\"荔浦市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (24, '海南省', NULL, NULL, '[{\"cityName\":\"海口市\",\"cityType\":\"地级市\"},{\"cityName\":\"三亚市\",\"cityType\":\"地级市\"},{\"cityName\":\"三沙市\",\"cityType\":\"地级市\"},{\"cityName\":\"儋州市\",\"cityType\":\"地级市\"},{\"cityName\":\"文昌市\",\"cityType\":\"县级市\"},{\"cityName\":\"琼海市\",\"cityType\":\"县级市\"},{\"cityName\":\"万宁市\",\"cityType\":\"县级市\"},{\"cityName\":\"东方市\",\"cityType\":\"县级市\"},{\"cityName\":\"五指山市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (25, '四川省', NULL, NULL, '[{\"cityName\":\"成都市\",\"cityType\":\"地级市\"},{\"cityName\":\"广元市\",\"cityType\":\"县级市\"},{\"cityName\":\"绵阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"德阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"南充市\",\"cityType\":\"县级市\"},{\"cityName\":\"广安市\",\"cityType\":\"县级市\"},{\"cityName\":\"遂宁市\",\"cityType\":\"县级市\"},{\"cityName\":\"内江市\",\"cityType\":\"县级市\"},{\"cityName\":\"乐山市\",\"cityType\":\"县级市\"},{\"cityName\":\"自贡市\",\"cityType\":\"县级市\"},{\"cityName\":\"泸州市\",\"cityType\":\"县级市\"},{\"cityName\":\"宜宾市\",\"cityType\":\"县级市\"},{\"cityName\":\"攀枝花市\",\"cityType\":\"县级市\"},{\"cityName\":\"巴中市\",\"cityType\":\"县级市\"},{\"cityName\":\"达州市\",\"cityType\":\"县级市\"},{\"cityName\":\"资阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"眉山市\",\"cityType\":\"县级市\"},{\"cityName\":\"雅安市\",\"cityType\":\"县级市\"},{\"cityName\":\"崇州市\",\"cityType\":\"县级市\"},{\"cityName\":\"邛崃市\",\"cityType\":\"县级市\"},{\"cityName\":\"都江堰市\",\"cityType\":\"县级市\"},{\"cityName\":\"彭州市\",\"cityType\":\"县级市\"},{\"cityName\":\"江油市\",\"cityType\":\"县级市\"},{\"cityName\":\"什邡市\",\"cityType\":\"县级市\"},{\"cityName\":\"广汉市\",\"cityType\":\"县级市\"},{\"cityName\":\"绵竹市\",\"cityType\":\"县级市\"},{\"cityName\":\"阆中市\",\"cityType\":\"县级市\"},{\"cityName\":\"华蓥市\",\"cityType\":\"县级市\"},{\"cityName\":\"峨眉山市\",\"cityType\":\"县级市\"},{\"cityName\":\"万源市\",\"cityType\":\"县级市\"},{\"cityName\":\"简阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"西昌市\",\"cityType\":\"县级市\"},{\"cityName\":\"康定市\",\"cityType\":\"县级市\"},{\"cityName\":\"马尔康市\",\"cityType\":\"县级市\"},{\"cityName\":\"隆昌市\",\"cityType\":\"县级市\"},{\"cityName\":\"射洪市\",\"cityType\":\"县级市\"},{\"cityName\":\"会理市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (26, '贵州省', NULL, NULL, '[{\"cityName\":\"贵阳市\",\"cityType\":\"地级市\"},{\"cityName\":\"六盘水市\",\"cityType\":\"地级市\"},{\"cityName\":\"遵义市\",\"cityType\":\"地级市\"},{\"cityName\":\"安顺市\",\"cityType\":\"地级市\"},{\"cityName\":\"毕节市\",\"cityType\":\"地级市\"},{\"cityName\":\"铜仁市\",\"cityType\":\"地级市\"},{\"cityName\":\"清镇市\",\"cityType\":\"县级市\"},{\"cityName\":\"赤水市\",\"cityType\":\"县级市\"},{\"cityName\":\"仁怀市\",\"cityType\":\"县级市\"},{\"cityName\":\"凯里市\",\"cityType\":\"县级市\"},{\"cityName\":\"都匀市\",\"cityType\":\"县级市\"},{\"cityName\":\"兴义市\",\"cityType\":\"县级市\"},{\"cityName\":\"福泉市\",\"cityType\":\"县级市\"},{\"cityName\":\"盘州市\",\"cityType\":\"县级市\"},{\"cityName\":\"兴仁市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (27, '云南省', NULL, NULL, '[{\"cityName\":\"昆明市\",\"cityType\":\"地级市\"},{\"cityName\":\"曲靖市\",\"cityType\":\"地级市\"},{\"cityName\":\"玉溪市\",\"cityType\":\"地级市\"},{\"cityName\":\"丽江市\",\"cityType\":\"地级市\"},{\"cityName\":\"昭通市\",\"cityType\":\"地级市\"},{\"cityName\":\"普洱市\",\"cityType\":\"地级市\"},{\"cityName\":\"临沧市\",\"cityType\":\"地级市\"},{\"cityName\":\"保山市\",\"cityType\":\"地级市\"},{\"cityName\":\"安宁市\",\"cityType\":\"县级市\"},{\"cityName\":\"宣威市\",\"cityType\":\"县级市\"},{\"cityName\":\"芒市\",\"cityType\":\"县级市\"},{\"cityName\":\"瑞丽市\",\"cityType\":\"县级市\"},{\"cityName\":\"大理市\",\"cityType\":\"县级市\"},{\"cityName\":\"楚雄市\",\"cityType\":\"县级市\"},{\"cityName\":\"个旧市\",\"cityType\":\"县级市\"},{\"cityName\":\"开远市\",\"cityType\":\"县级市\"},{\"cityName\":\"蒙自市\",\"cityType\":\"县级市\"},{\"cityName\":\"弥勒市\",\"cityType\":\"县级市\"},{\"cityName\":\"景洪市\",\"cityType\":\"县级市\"},{\"cityName\":\"文山市\",\"cityType\":\"县级市\"},{\"cityName\":\"香格里拉市\",\"cityType\":\"县级市\"},{\"cityName\":\"腾冲市\",\"cityType\":\"县级市\"},{\"cityName\":\"水富市\",\"cityType\":\"县级市\"},{\"cityName\":\"澄江市\",\"cityType\":\"县级市\"},{\"cityName\":\"泸水市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (28, '陕西省', NULL, NULL, '[{\"cityName\":\"西安市\",\"cityType\":\"地级市\"},{\"cityName\":\"延安市\",\"cityType\":\"县级市\"},{\"cityName\":\"铜川市\",\"cityType\":\"县级市\"},{\"cityName\":\"渭南市\",\"cityType\":\"县级市\"},{\"cityName\":\"咸阳市\",\"cityType\":\"县级市\"},{\"cityName\":\"宝鸡市\",\"cityType\":\"县级市\"},{\"cityName\":\"汉中市\",\"cityType\":\"县级市\"},{\"cityName\":\"榆林市\",\"cityType\":\"县级市\"},{\"cityName\":\"商洛市\",\"cityType\":\"县级市\"},{\"cityName\":\"安康市\",\"cityType\":\"县级市\"},{\"cityName\":\"韩城市\",\"cityType\":\"县级市\"},{\"cityName\":\"华阴市\",\"cityType\":\"县级市\"},{\"cityName\":\"兴平市\",\"cityType\":\"县级市\"},{\"cityName\":\"彬州市\",\"cityType\":\"县级市\"},{\"cityName\":\"神木市\",\"cityType\":\"县级市\"},{\"cityName\":\"子长市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (29, '甘肃省', NULL, NULL, '[{\"cityName\":\"兰州市\",\"cityType\":\"地级市\"},{\"cityName\":\"嘉峪关市\",\"cityType\":\"地级市\"},{\"cityName\":\"金昌市\",\"cityType\":\"地级市\"},{\"cityName\":\"白银市\",\"cityType\":\"地级市\"},{\"cityName\":\"天水市\",\"cityType\":\"地级市\"},{\"cityName\":\"酒泉市\",\"cityType\":\"地级市\"},{\"cityName\":\"张掖市\",\"cityType\":\"地级市\"},{\"cityName\":\"武威市\",\"cityType\":\"地级市\"},{\"cityName\":\"庆阳市\",\"cityType\":\"地级市\"},{\"cityName\":\"平凉市\",\"cityType\":\"地级市\"},{\"cityName\":\"定西市\",\"cityType\":\"地级市\"},{\"cityName\":\"陇南市\",\"cityType\":\"地级市\"},{\"cityName\":\"玉门市\",\"cityType\":\"县级市\"},{\"cityName\":\"敦煌市\",\"cityType\":\"县级市\"},{\"cityName\":\"临夏市\",\"cityType\":\"县级市\"},{\"cityName\":\"合作市\",\"cityType\":\"县级市\"},{\"cityName\":\"华亭市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (30, '青海省', NULL, NULL, '[{\"cityName\":\"西宁市\",\"cityType\":\"地级市\"},{\"cityName\":\"海东市\",\"cityType\":\"地级市\"},{\"cityName\":\"格尔木市\",\"cityType\":\"县级市\"},{\"cityName\":\"德令哈市\",\"cityType\":\"县级市\"},{\"cityName\":\"玉树市\",\"cityType\":\"县级市\"},{\"cityName\":\"茫崖市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (31, '西藏自治区', NULL, NULL, '[{\"cityName\":\"拉萨市\",\"cityType\":\"地级市\"},{\"cityName\":\"日喀则市\",\"cityType\":\"地级市\"},{\"cityName\":\"昌都市\",\"cityType\":\"地级市\"},{\"cityName\":\"林芝市\",\"cityType\":\"地级市\"},{\"cityName\":\"山南市\",\"cityType\":\"地级市\"},{\"cityName\":\"那曲市\",\"cityType\":\"地级市\"}]');
INSERT INTO `address` VALUES (32, '宁夏回族自治区', NULL, NULL, '[{\"cityName\":\"银川市\",\"cityType\":\"地级市\"},{\"cityName\":\"石嘴山市\",\"cityType\":\"地级市\"},{\"cityName\":\"吴忠市\",\"cityType\":\"地级市\"},{\"cityName\":\"中卫市\",\"cityType\":\"地级市\"},{\"cityName\":\"固原市\",\"cityType\":\"地级市\"},{\"cityName\":\"灵武市\",\"cityType\":\"县级市\"},{\"cityName\":\"青铜峡市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (33, '新疆维吾尔自治区', NULL, NULL, '[{\"cityName\":\"乌鲁木齐市\",\"cityType\":\"地级市\"},{\"cityName\":\"克拉玛依市\",\"cityType\":\"地级市\"},{\"cityName\":\"吐鲁番市\",\"cityType\":\"地级市\"},{\"cityName\":\"哈密市\",\"cityType\":\"地级市\"},{\"cityName\":\"喀什市\",\"cityType\":\"县级市\"},{\"cityName\":\"阿克苏市\",\"cityType\":\"县级市\"},{\"cityName\":\"库车市\",\"cityType\":\"县级市\"},{\"cityName\":\"和田市\",\"cityType\":\"县级市\"},{\"cityName\":\"阿图什市\",\"cityType\":\"县级市\"},{\"cityName\":\"阿拉山口市\",\"cityType\":\"县级市\"},{\"cityName\":\"博乐市\",\"cityType\":\"县级市\"},{\"cityName\":\"昌吉市\",\"cityType\":\"县级市\"},{\"cityName\":\"阜康市\",\"cityType\":\"县级市\"},{\"cityName\":\"库尔勒市\",\"cityType\":\"县级市\"},{\"cityName\":\"伊宁市\",\"cityType\":\"县级市\"},{\"cityName\":\"奎屯市\",\"cityType\":\"县级市\"},{\"cityName\":\"塔城市\",\"cityType\":\"县级市\"},{\"cityName\":\"乌苏市\",\"cityType\":\"县级市\"},{\"cityName\":\"阿勒泰市\",\"cityType\":\"县级市\"},{\"cityName\":\"霍尔果斯市\",\"cityType\":\"县级市\"},{\"cityName\":\"石河子市\",\"cityType\":\"县级市\"},{\"cityName\":\"阿拉尔市\",\"cityType\":\"县级市\"},{\"cityName\":\"图木舒克市\",\"cityType\":\"县级市\"},{\"cityName\":\"五家渠市\",\"cityType\":\"县级市\"},{\"cityName\":\"北屯市\",\"cityType\":\"县级市\"},{\"cityName\":\"铁门关市\",\"cityType\":\"县级市\"},{\"cityName\":\"双河市\",\"cityType\":\"县级市\"},{\"cityName\":\"可克达拉市\",\"cityType\":\"县级市\"},{\"cityName\":\"昆玉市\",\"cityType\":\"县级市\"},{\"cityName\":\"胡杨河市\",\"cityType\":\"县级市\"}]');
INSERT INTO `address` VALUES (34, '台湾', NULL, NULL, '[{\"cityName\":\"台北市\",\"cityType\":\"地级市\"},{\"cityName\":\"新北市\",\"cityType\":\"地级市\"},{\"cityName\":\"桃园市\",\"cityType\":\"地级市\"},{\"cityName\":\"台中市\",\"cityType\":\"地级市\"},{\"cityName\":\"台南市\",\"cityType\":\"地级市\"},{\"cityName\":\"高雄市\",\"cityType\":\"地级市\"},{\"cityName\":\"基隆市\",\"cityType\":\"县级市\"},{\"cityName\":\"新竹市\",\"cityType\":\"县级市\"},{\"cityName\":\"嘉义市\",\"cityType\":\"县级市\"}]');

-- ----------------------------
-- Table structure for wx_user
-- ----------------------------
DROP TABLE IF EXISTS `wx_user`;
CREATE TABLE `wx_user`  (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `user` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '账号',
  `password` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '密码',
  `sex` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '性别',
  `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '邮箱',
  `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  `avatar` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '头像地址',
  `role` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '角色',
  `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL COMMENT '姓名',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 2 CHARACTER SET = utf8 COLLATE = utf8_unicode_ci COMMENT = '用户信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of wx_user
-- ----------------------------
INSERT INTO `wx_user` VALUES (1, '1', '1', '1', '1', '2024-11-08 17:10:50', 'https://pic.meitukk.com/uploads/meitukk/dm/20230621/230621045810441.jpg', '1', '1');

SET FOREIGN_KEY_CHECKS = 1;
